<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
    <ItemGroup>
    <PackageReference Include="NodaTime.Global" Version="1.0.1" />
    <PackageReference Include="Microsoft.Build.Framework" Version="17.8.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
     <PackageReference Include="NodatimePackage" Version="1.1.1" />
  </ItemGroup>

</Project>
